// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/joy/workspace/gopath/src/study/C/hello.go:1:1
package main

//#include <hello.h>
import _ "unsafe"

import "fmt"

//export SayHello
func SayHello(s * /*line :9:18*/_Ctype_char /*line :9:24*/) {
	fmt.Print(( /*line :10:12*/_Cfunc_GoString /*line :10:21*/)(s))
}

//export add
func add(a, b  /*line :14:15*/_Ctype_int /*line :14:20*/)  /*line :14:22*/_Ctype_int /*line :14:27*/  {
	return a+b
}

func main() {
	( /*line :19:2*/_Cfunc_SayHello /*line :19:11*/)(( /*line :19:13*/_Cfunc_CString /*line :19:21*/)("Hello, World\n"))
}